#!/usr/bin/env bash
# Regenerate the Python SDK models from apps/api's OpenAPI schema.
#
# Mirrors packages/api-client/scripts/generate.sh, but emits the schema
# *in-process* via `app.openapi()` rather than booting uvicorn — the schema
# is pure route metadata, so no DB / Supabase / AWS / network is touched.
# The emitted models land in src/ovb/_generated/models.py (gitignored), the
# machine-emitted half of the SDK that ovb/sdk.py wraps by hand.

set -euo pipefail

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PKG_DIR="$( cd "${SCRIPT_DIR}/.." && pwd )"
REPO_ROOT="$( cd "${PKG_DIR}/../.." && pwd )"
API_DIR="${REPO_ROOT}/apps/api"
SCHEMA_FILE="${PKG_DIR}/openapi.json"
OUT_DIR="${PKG_DIR}/src/ovb/_generated"
OUT_FILE="${OUT_DIR}/models.py"

if ! command -v uv >/dev/null 2>&1; then
  echo "error: uv is not installed — see apps/api/pyproject.toml (T02)." >&2
  exit 1
fi

echo "→ Emitting OpenAPI schema in-process from apps/api…"
( cd "${API_DIR}" && uv run --quiet python -c \
  'import json,sys; from app.main import app; json.dump(app.openapi(), sys.stdout)' \
) > "${SCHEMA_FILE}"

echo "→ Generating pydantic v2 models into ${OUT_FILE#${REPO_ROOT}/}…"
mkdir -p "${OUT_DIR}"
( cd "${PKG_DIR}" && uv run --quiet datamodel-codegen \
  --input "${SCHEMA_FILE}" \
  --input-file-type openapi \
  --output "${OUT_FILE}" \
  --output-model-type pydantic_v2.BaseModel \
  --target-python-version 3.13 \
  --use-standard-collections \
  --use-union-operator \
  --use-annotated \
  --field-constraints \
  --use-schema-description \
  --collapse-root-models \
  --disable-timestamp )

# Keep _generated importable as a package even though models.py is gitignored.
cat > "${OUT_DIR}/__init__.py" <<'EOF'
"""Machine-emitted SDK models — regenerated by scripts/generate.sh. Do not edit."""

from ovb._generated.models import *  # noqa: F401,F403
EOF

rm -f "${SCHEMA_FILE}"
echo "✓ ovb SDK models generated."
