-- 0045_itinerary_day_notes.sql
-- Export feature — per-day trip notes ("what to bring", tips).
--
-- One row per (itinerary, local day). Three authorship sources:
--   'advisor'  — hand-written via PUT /itinerary/{id}/day-notes/{date}.
--                Never auto-touched by export generation; nodes_hash is NULL
--                because the content is not derived from the day's nodes.
--   'llm'      — generated by the export day-notes service (Bedrock converse)
--                from graph data ONLY (no dossier/OSINT/profile input, ever).
--   'fallback' — deterministic rule-based notes when Bedrock is unavailable.
-- For 'llm'/'fallback' rows, nodes_hash fingerprints the day's node content so
-- a stale row regenerates on the next export; advisor rows are used verbatim.
--
-- Authorization is enforced in the API service layer (the API connects as the
-- owner role, bypassing RLS). The RLS policy below is defense-in-depth per the
-- 0019/0037 idiom. Content is traveler-safe by construction, so the read rule
-- mirrors itinerary readability (client ownership). Idempotent: safe to re-run.

create table if not exists public.itinerary_day_notes (
    id           uuid primary key default gen_random_uuid(),
    itinerary_id uuid not null references public.itineraries (id) on delete cascade,
    day_date     date not null,
    source       text not null check (source in ('advisor', 'llm', 'fallback')),
    -- NULL for advisor-authored rows (not hash-managed); required for generated
    -- rows so staleness is detectable.
    nodes_hash   text check (source = 'advisor' or nodes_hash is not null),
    content      jsonb not null default '{}'::jsonb,  -- {"bring": [...], "tips": [...]}
    updated_by   uuid references auth.users (id) on delete set null,
    generated_at timestamptz not null default now(),
    unique (itinerary_id, day_date)
);

create index if not exists itinerary_day_notes_itinerary_idx
    on public.itinerary_day_notes (itinerary_id, day_date);

alter table public.itinerary_day_notes enable row level security;

drop policy if exists "itinerary_day_notes_collab_select" on public.itinerary_day_notes;
create policy "itinerary_day_notes_collab_select" on public.itinerary_day_notes
    for select to authenticated
    using (exists (
        select 1 from public.itineraries i
        join public.clients c on c.id = i.client_id
        where i.id = itinerary_id
          and (c.owner_id = auth.uid() or c.auth_user_id = auth.uid())
    ));
