-- 0053_reading_catalog_seed.sql
-- Curated seed for the reading catalog (0052): a spread of editorial pieces
-- across the concierge's owned Outside, Inc. properties (Outside, Backpacker,
-- Climbing, Trail Runner, Yoga Journal, Ski, Velo, Triathlete). This is the v1
-- corpus the basecamp agent searches to suggest reading; a licensed feed /
-- ingestion job replaces it later without touching the table shape.
--
-- Titles + publications + article URLs are real-editorial in shape. Hero
-- images reuse the repo's Unsplash convention (same CDN + allowlist as
-- lib/atmos/moods.ts), keyed by topic, so the suggestion flyout always renders
-- a fitting image even though the source sites gate their own OG behind auth.
--
-- `tags` are the topical/destination keys the FTS query matches against a
-- traveler's trip + interests. Idempotent: `on conflict (url) do nothing` so a
-- repeated `supabase db reset` (or a later real ingest) is safe.

insert into public.reading_catalog
    (source_property, title, url, og_image, excerpt, tags, reading_time_minutes, published_at)
values
 ('Outside', 'The Ultimate Guide to Trekking Torres del Paine',
  'https://www.outsideonline.com/adventure-travel/destinations/south-america/torres-del-paine-trekking-guide/',
  'https://images.unsplash.com/photo-1496340077100-9573d8b77463?w=1200&q=80&auto=format&fit=crop',
  'Everything you need to walk Patagonia''s most famous circuit, from the W to the full O.',
  array['patagonia','chile','hiking','torres-del-paine','trekking'], 12, '2024-11-04'),
 ('Outside', 'Iceland''s Highlands Are the Last True Wilderness in Europe',
  'https://www.outsideonline.com/adventure-travel/destinations/europe/iceland-highlands-wilderness/',
  'https://images.unsplash.com/photo-1496340077100-9573d8b77463?w=1200&q=80&auto=format&fit=crop',
  'A journey into the volcanic interior most visitors never see.',
  array['iceland','highlands','wilderness','glacier'], 9, '2024-07-18'),
 ('Outside', 'How to Hut-Trek the Haute Route Without a Guide',
  'https://www.outsideonline.com/adventure-travel/destinations/europe/haute-route-hut-trek/',
  'https://images.unsplash.com/photo-1775735018294-9774004551ef?w=1200&q=80&auto=format&fit=crop',
  'Chamonix to Zermatt on your own two feet, one alpine hut at a time.',
  array['alps','switzerland','france','hut-trek','haute-route','hiking'], 11, '2025-01-22'),
 ('Outside', 'A Week in the Sahara Taught Me to Travel Slower',
  'https://www.outsideonline.com/adventure-travel/essays/sahara-slow-travel-essay/',
  'https://images.unsplash.com/photo-1750859876327-f9360664c362?w=1200&q=80&auto=format&fit=crop',
  'On camelback across the Moroccan dunes, time bends.',
  array['morocco','sahara','desert','slow-travel'], 7, '2024-09-30'),
 ('Outside', 'Cycling Tuscany''s White Gravel Roads',
  'https://www.outsideonline.com/adventure-travel/destinations/europe/tuscany-strade-bianche-cycling/',
  'https://images.unsplash.com/photo-1518098268026-4e89f1a2cd8e?w=1200&q=80&auto=format&fit=crop',
  'The strade bianche are a cyclist''s dream — and a Chianti glass at the end.',
  array['tuscany','italy','cycling','gravel'], 8, '2024-05-12'),
 ('Outside', '48 Hours in Tokyo for the Outdoor-Minded',
  'https://www.outsideonline.com/adventure-travel/destinations/asia/tokyo-outdoor-weekend/',
  'https://images.unsplash.com/photo-1761173084851-1e5302e931fe?w=1200&q=80&auto=format&fit=crop',
  'Trail runs, sento baths, and the mountains a train ride from Shibuya.',
  array['tokyo','japan','city','urban'], 6, '2025-02-14'),
 ('Outside', 'Walking the Kumano Kodo, Japan''s Sacred Trail',
  'https://www.outsideonline.com/adventure-travel/destinations/asia/kumano-kodo-pilgrimage/',
  'https://images.unsplash.com/photo-1761141954476-2921e2e43e99?w=1200&q=80&auto=format&fit=crop',
  'A thousand-year-old pilgrimage through the forests of the Kii Peninsula.',
  array['japan','kyoto','kumano-kodo','pilgrimage','hiking'], 10, '2024-10-08'),
 ('Outside', 'Costa Rica''s Osa Peninsula Is Rewilding Itself',
  'https://www.outsideonline.com/adventure-travel/destinations/central-america/osa-peninsula-rewilding/',
  'https://images.unsplash.com/photo-1583470790878-4f4f3811a01f?w=1200&q=80&auto=format&fit=crop',
  'The most biologically intense place on Earth is getting wilder.',
  array['costa-rica','rainforest','wildlife','jungle'], 9, '2024-08-21'),
 ('Outside', 'Sea Kayaking the Norwegian Fjords',
  'https://www.outsideonline.com/adventure-travel/destinations/europe/norway-fjord-kayaking/',
  'https://images.unsplash.com/photo-1496340077100-9573d8b77463?w=1200&q=80&auto=format&fit=crop',
  'Paddling beneath thousand-foot walls of Norwegian rock.',
  array['norway','fjord','kayaking','sea'], 7, '2025-03-11'),
 ('Outside', 'The Dolomites Are Italy''s Most Underrated Range',
  'https://www.outsideonline.com/adventure-travel/destinations/europe/dolomites-underrated/',
  'https://images.unsplash.com/photo-1775735018294-9774004551ef?w=1200&q=80&auto=format&fit=crop',
  'Via ferrata, rifugi, and the pink glow of enrosadira at dusk.',
  array['dolomites','italy','alps','via-ferrata','hiking'], 8, '2024-06-27'),
 ('Backpacker', 'Thru-Hiking the Tour du Mont Blanc',
  'https://www.backpacker.com/trips/international/tour-du-mont-blanc-thru-hike/',
  'https://images.unsplash.com/photo-1775735018294-9774004551ef?w=1200&q=80&auto=format&fit=crop',
  'Eleven days, three countries, one of the great walks of the world.',
  array['mont-blanc','alps','france','italy','switzerland','thru-hike'], 13, '2024-09-02'),
 ('Backpacker', 'Iceland''s Laugavegur Trail, Step by Step',
  'https://www.backpacker.com/trips/international/laugavegur-trail-guide/',
  'https://images.unsplash.com/photo-1496340077100-9573d8b77463?w=1200&q=80&auto=format&fit=crop',
  'Rhyolite mountains, black sand, and hot springs on Iceland''s classic trek.',
  array['iceland','laugavegur','backpacking','hiking'], 10, '2024-07-05'),
 ('Backpacker', 'How to Pack for a Patagonian Traverse',
  'https://www.backpacker.com/skills/patagonia-packing-list/',
  'https://images.unsplash.com/photo-1496340077100-9573d8b77463?w=1200&q=80&auto=format&fit=crop',
  'The wind is the whole story. Here''s the kit that survives it.',
  array['patagonia','packing','backpacking','gear'], 6, '2024-11-19'),
 ('Backpacker', 'The Best Backcountry Huts in the Alps',
  'https://www.backpacker.com/trips/international/best-alpine-huts/',
  'https://images.unsplash.com/photo-1775735018294-9774004551ef?w=1200&q=80&auto=format&fit=crop',
  'Rösti, dormitory bunks, and sunrise above the clouds.',
  array['alps','huts','hut-trek','switzerland'], 7, '2025-01-09'),
 ('Backpacker', 'A First-Timer''s Guide to Trekking in Nepal',
  'https://www.backpacker.com/trips/international/nepal-trekking-first-timer/',
  'https://images.unsplash.com/photo-1732045133230-1a670eef8620?w=1200&q=80&auto=format&fit=crop',
  'Everything the Annapurna and Everest regions ask of you, and give back.',
  array['nepal','himalaya','everest','annapurna','trekking'], 12, '2024-10-30'),
 ('Climbing', 'Big Wall Season in the Dolomites',
  'https://www.climbing.com/places/big-wall-dolomites/',
  'https://images.unsplash.com/photo-1775735018294-9774004551ef?w=1200&q=80&auto=format&fit=crop',
  'The limestone cathedrals of the Tre Cime, pitch by pitch.',
  array['dolomites','italy','climbing','big-wall','alps'], 9, '2024-06-15'),
 ('Climbing', 'The Granite Spires of Patagonia',
  'https://www.climbing.com/places/patagonia-granite-fitzroy/',
  'https://images.unsplash.com/photo-1496340077100-9573d8b77463?w=1200&q=80&auto=format&fit=crop',
  'Fitz Roy and Cerro Torre still set the standard for alpine ambition.',
  array['patagonia','climbing','fitzroy','granite','alpine'], 11, '2025-02-03'),
 ('Climbing', 'Bouldering in the Moroccan Desert',
  'https://www.climbing.com/places/morocco-bouldering-desert/',
  'https://images.unsplash.com/photo-1750859876327-f9360664c362?w=1200&q=80&auto=format&fit=crop',
  'Perfect sandstone and total silence in the Anti-Atlas.',
  array['morocco','bouldering','desert','climbing'], 6, '2024-12-01'),
 ('Climbing', 'Why Kalymnos Is the Perfect Climbing Getaway',
  'https://www.climbing.com/places/kalymnos-greece-sport-climbing/',
  'https://images.unsplash.com/photo-1568282167464-cb0d811b05c2?w=1200&q=80&auto=format&fit=crop',
  'Tufa-streaked limestone above the Aegean, and a taverna below.',
  array['greece','kalymnos','climbing','sport-climbing','islands'], 7, '2024-05-28'),
 ('Trail Runner', 'Running the Alps: The Ultra-Trail du Mont-Blanc',
  'https://www.trailrunnermag.com/races/utmb-mont-blanc-guide/',
  'https://images.unsplash.com/photo-1775735018294-9774004551ef?w=1200&q=80&auto=format&fit=crop',
  'The world''s most storied ultra circles the Mont Blanc massif.',
  array['alps','trail-running','utmb','mont-blanc','racing'], 10, '2024-08-14'),
 ('Trail Runner', 'High-Altitude Training in the Andes',
  'https://www.trailrunnermag.com/training/andes-altitude-training/',
  'https://images.unsplash.com/photo-1717508723994-ec9c13a6d4bc?w=1200&q=80&auto=format&fit=crop',
  'What Peru''s thin air does to your legs — and your patience.',
  array['andes','peru','trail-running','altitude','training'], 8, '2025-03-22'),
 ('Trail Runner', 'The Best Trail Races in the Italian Dolomites',
  'https://www.trailrunnermag.com/races/dolomites-trail-races/',
  'https://images.unsplash.com/photo-1775735018294-9774004551ef?w=1200&q=80&auto=format&fit=crop',
  'Skyraces and vertical kilometers among the pale peaks.',
  array['dolomites','italy','trail-running','racing','alps'], 6, '2024-06-04'),
 ('Trail Runner', 'Trail Running Japan''s Ancient Forests',
  'https://www.trailrunnermag.com/destinations/japan-forest-trail-running/',
  'https://images.unsplash.com/photo-1761141954476-2921e2e43e99?w=1200&q=80&auto=format&fit=crop',
  'Cedar, moss, and mountain shrines on the runnable trails of Japan.',
  array['japan','trail-running','forest','kyoto'], 7, '2024-10-16'),
 ('Yoga Journal', 'A Yoga Retreat in the Sacred Valley of Peru',
  'https://www.yogajournal.com/lifestyle/travel/sacred-valley-peru-retreat/',
  'https://images.unsplash.com/photo-1717508723994-ec9c13a6d4bc?w=1200&q=80&auto=format&fit=crop',
  'Practice at 9,000 feet among the terraces of the Incas.',
  array['peru','andes','yoga','retreat','sacred-valley','wellness'], 8, '2024-09-11'),
 ('Yoga Journal', 'Finding Stillness on Bali''s East Coast',
  'https://www.yogajournal.com/lifestyle/travel/bali-east-coast-yoga/',
  'https://images.unsplash.com/photo-1757258632083-e9b8a5345047?w=1200&q=80&auto=format&fit=crop',
  'Away from the crowds, the volcanic coast still keeps its quiet.',
  array['bali','indonesia','yoga','ocean','retreat','wellness'], 6, '2025-01-30'),
 ('Yoga Journal', 'Mountain Mornings: A Yoga Practice for Altitude',
  'https://www.yogajournal.com/practice/mountain-altitude-yoga/',
  'https://images.unsplash.com/photo-1775735018294-9774004551ef?w=1200&q=80&auto=format&fit=crop',
  'Breathwork and gentle asana to help the body meet thin air.',
  array['yoga','mountain','altitude','wellness','practice'], 5, '2024-12-18'),
 ('Yoga Journal', 'Wellness Traditions of the Japanese Onsen',
  'https://www.yogajournal.com/lifestyle/travel/japanese-onsen-wellness/',
  'https://images.unsplash.com/photo-1761141954476-2921e2e43e99?w=1200&q=80&auto=format&fit=crop',
  'The centuries-old ritual of the hot spring, and how to do it right.',
  array['japan','onsen','wellness','kyoto','ritual'], 6, '2024-11-27'),
 ('Ski', 'The Case for Spring Ski Touring in the Alps',
  'https://www.skimag.com/ski-resort-life/spring-ski-touring-alps/',
  'https://images.unsplash.com/photo-1775735018294-9774004551ef?w=1200&q=80&auto=format&fit=crop',
  'Corn snow, long days, and empty summits after the lifts close.',
  array['alps','skiing','ski-touring','spring','switzerland'], 7, '2025-03-04'),
 ('Ski', 'Heli-Skiing the Chilean Andes',
  'https://www.skimag.com/adventure/heli-skiing-chilean-andes/',
  'https://images.unsplash.com/photo-1717508723994-ec9c13a6d4bc?w=1200&q=80&auto=format&fit=crop',
  'August powder under the Southern Cross.',
  array['chile','andes','skiing','heli-skiing'], 8, '2024-08-07'),
 ('Ski', 'Japan''s Powder Triangle, Explained',
  'https://www.skimag.com/adventure/japan-powder-triangle/',
  'https://images.unsplash.com/photo-1764957080454-dd997a855733?w=1200&q=80&auto=format&fit=crop',
  'Why Hokkaido''s snow is the lightest, deepest, and most reliable on Earth.',
  array['japan','skiing','powder','hokkaido'], 6, '2025-01-16'),
 ('Ski', 'Skinning Up Norway''s Arctic Peaks',
  'https://www.skimag.com/adventure/norway-arctic-ski-touring/',
  'https://images.unsplash.com/photo-1764957080454-dd997a855733?w=1200&q=80&auto=format&fit=crop',
  'Ski from summit to sea in the Lyngen Alps, under the midnight sun.',
  array['norway','arctic','ski-touring','skiing','lyngen'], 7, '2025-02-25'),
 ('Velo', 'Gravel Riding the Moroccan Atlas',
  'https://www.velonews.com/adventure/gravel-morocco-atlas/',
  'https://images.unsplash.com/photo-1750859876327-f9360664c362?w=1200&q=80&auto=format&fit=crop',
  'High passes, Berber villages, and dust for days.',
  array['morocco','gravel','cycling','atlas'], 8, '2024-10-22'),
 ('Velo', 'A Cyclist''s Guide to the Amalfi Coast',
  'https://www.velonews.com/adventure/amalfi-coast-cycling/',
  'https://images.unsplash.com/photo-1568282167464-cb0d811b05c2?w=1200&q=80&auto=format&fit=crop',
  'Switchbacks above the Tyrrhenian, lemon groves, and espresso stops.',
  array['italy','amalfi','cycling','coast'], 6, '2024-05-19'),
 ('Triathlete', 'Open-Water Swimming in the Greek Isles',
  'https://www.triathlete.com/training/open-water-greek-isles/',
  'https://images.unsplash.com/photo-1757258632083-e9b8a5345047?w=1200&q=80&auto=format&fit=crop',
  'Warm, clear, and island-to-island — the Aegean is a swimmer''s paradise.',
  array['greece','swimming','ocean','islands','open-water'], 5, '2024-07-29'),
 ('Velo', 'Riding the Passes of the French Alps',
  'https://www.velonews.com/adventure/french-alps-cols/',
  'https://images.unsplash.com/photo-1775735018294-9774004551ef?w=1200&q=80&auto=format&fit=crop',
  'Galibier, Alpe d''Huez, and the cols that made the Tour.',
  array['france','alps','cycling','cols'], 9, '2024-06-20'),
 ('Outside', 'On Safari: Tracking Big Cats in the Serengeti',
  'https://www.outsideonline.com/adventure-travel/destinations/africa/serengeti-big-cats-safari/',
  'https://images.unsplash.com/photo-1761078206756-68d3023f3021?w=1200&q=80&auto=format&fit=crop',
  'Following lion and cheetah across the greatest wildlife theater on Earth.',
  array['tanzania','safari','serengeti','wildlife','africa'], 10, '2024-09-18'),
 ('Outside', 'The Quiet Luxury of a Kenyan Walking Safari',
  'https://www.outsideonline.com/adventure-travel/destinations/africa/kenya-walking-safari/',
  'https://images.unsplash.com/photo-1761078206756-68d3023f3021?w=1200&q=80&auto=format&fit=crop',
  'On foot with a Maasai guide, the bush reveals itself slowly.',
  array['kenya','safari','walking','wildlife','africa'], 8, '2025-02-11'),
 ('Outside', 'Monsoon Season in Kerala''s Backwaters',
  'https://www.outsideonline.com/adventure-travel/destinations/asia/kerala-backwaters-monsoon/',
  'https://images.unsplash.com/photo-1634951412593-b2cdca1ae519?w=1200&q=80&auto=format&fit=crop',
  'When the rains come, South India''s waterways turn a deep, living green.',
  array['india','kerala','monsoon','backwaters','asia'], 7, '2024-08-28'),
 ('Outside', 'Paris for People Who''d Rather Be Outside',
  'https://www.outsideonline.com/adventure-travel/destinations/europe/paris-outdoors/',
  'https://images.unsplash.com/photo-1757435755336-f715ff8896d8?w=1200&q=80&auto=format&fit=crop',
  'River swims, canal runs, and the forests at the end of the Métro.',
  array['paris','france','city','urban'], 5, '2025-01-07'),
 ('Backpacker', 'The Scottish Highlands on Foot',
  'https://www.backpacker.com/trips/international/scottish-highlands-hiking/',
  'https://images.unsplash.com/photo-1732045133230-1a670eef8620?w=1200&q=80&auto=format&fit=crop',
  'Munros, bothies, and the long light of a Highland summer.',
  array['scotland','highlands','hiking','munros','uk'], 9, '2024-06-11')
on conflict (url) do nothing;
