# generated by datamodel-codegen:
#   filename:  openapi.json

from __future__ import annotations

from datetime import date as date_aliased
from enum import StrEnum
from typing import Annotated, Any, Literal
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, EmailStr, Field, RootModel


class AdvisorItineraryClient(BaseModel):
    """
    Embedded client shape for the advisor roster row.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[UUID, Field(title='Id')]
    full_name: Annotated[str, Field(title='Full Name')]
    email: Annotated[EmailStr, Field(title='Email')]


class AnalysisDepth(StrEnum):
    """
    Mirrors the public.analysis_depth Postgres enum (0017).

    Explicitly chosen by the caller, never inferred (D-ANALYZE). ``shallow`` =
    structural only (no external calls); ``standard`` = physical-feasibility
    envelope (haversine drive-times). ``deep`` (live external data) is deferred
    for the MVP — the runner downgrades a ``deep`` request to ``standard``.
    """

    shallow = 'shallow'
    standard = 'standard'
    deep = 'deep'


class AnalysisStatus(StrEnum):
    """
    Mirrors the public.analysis_status Postgres enum (0017).

    Run state machine: ``queued`` -> ``running`` -> ``completed``, with
    ``failed`` / ``cancelled`` as terminal side-exits. Terminal states are
    immutable — the background runner checks status before each commit.
    """

    queued = 'queued'
    running = 'running'
    completed = 'completed'
    failed = 'failed'
    cancelled = 'cancelled'


class AnalysisSummaryResponse(BaseModel):
    id: Annotated[UUID, Field(title='Id')]
    itinerary_id: Annotated[UUID, Field(title='Itinerary Id')]
    status: AnalysisStatus
    depth: AnalysisDepth
    summary: Annotated[str | None, Field(title='Summary')]
    error_detail: Annotated[str | None, Field(title='Error Detail')]
    started_at: Annotated[AwareDatetime | None, Field(title='Started At')]
    completed_at: Annotated[AwareDatetime | None, Field(title='Completed At')]
    created_at: Annotated[AwareDatetime, Field(title='Created At')]


class AuthedHealthResponse(BaseModel):
    status: Annotated[str, Field(title='Status')]
    sub: Annotated[str, Field(title='Sub')]
    role: Annotated[str | None, Field(title='Role')] = None


class Value(RootModel[str]):
    root: Annotated[str, Field(max_length=256, min_length=1, title='Value')]


class Label(RootModel[str]):
    root: Annotated[str, Field(max_length=64, title='Label')]


class ClientCreateResponse(BaseModel):
    """
    Response for ``POST /clients`` on the successful path.

    The action_link from Supabase is deliberately omitted — it is a
    single-use login credential and must not cross the HTTP boundary.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    client_id: Annotated[UUID, Field(title='Client Id')]
    invite_email: Annotated[EmailStr, Field(title='Invite Email')]


class InviteStatus(StrEnum):
    pending = 'pending'
    consumed = 'consumed'
    cancelled = 'cancelled'
    none = 'none'


class ClientSessionSummary(BaseModel):
    """
    Row shape for ``GET /clients/{id}/sessions`` — one agent session.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[UUID, Field(title='Id')]
    started_at: Annotated[AwareDatetime, Field(title='Started At')]
    ended_at: Annotated[AwareDatetime | None, Field(title='Ended At')]
    last_turn_at: Annotated[AwareDatetime | None, Field(title='Last Turn At')]
    turn_count: Annotated[int, Field(title='Turn Count')]
    itinerary_id: Annotated[UUID | None, Field(title='Itinerary Id')]
    seeded_opener: Annotated[str | None, Field(title='Seeded Opener')]


class ClientSessionsResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    sessions: Annotated[list[ClientSessionSummary], Field(title='Sessions')]


class ClientSummary(BaseModel):
    """
    Row shape for ``GET /clients``.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[UUID, Field(title='Id')]
    full_name: Annotated[str, Field(title='Full Name')]
    email: Annotated[EmailStr, Field(title='Email')]
    has_dossier: Annotated[bool, Field(title='Has Dossier')]
    invite_status: Annotated[InviteStatus, Field(title='Invite Status')]
    created_at: Annotated[AwareDatetime, Field(title='Created At')]


class ContactChannel(StrEnum):
    """
    Mirrors the public.contact_channel Postgres enum from 0003_clients_dossiers.sql.
    """

    email = 'email'
    sms = 'sms'
    whatsapp = 'whatsapp'
    phone = 'phone'


class ContactKind(StrEnum):
    """
    Mirrors the public.contact_kind Postgres enum from 0013_client_contacts.sql.
    """

    phone_cell = 'phone_cell'
    phone_home = 'phone_home'
    phone_work = 'phone_work'
    whatsapp = 'whatsapp'
    signal = 'signal'
    telegram = 'telegram'
    imessage = 'imessage'
    instagram = 'instagram'
    linkedin = 'linkedin'
    x = 'x'
    facebook = 'facebook'
    wechat = 'wechat'
    other = 'other'


class CostKind(StrEnum):
    """
    Mirrors the public.cost_kind Postgres enum (0016).

    Whether a node's ``cost_amount`` is quoted per traveler (``per_person``)
    or as a single total for the node (``total``). Inventory providers that
    quote a whole-booking price (Duffel offer total, Ratehawk stay total) map
    to ``total``; OV-style per-person experiences map to ``per_person``.
    """

    per_person = 'per_person'
    total = 'total'


class CreateItineraryRequest(BaseModel):
    title: Annotated[str | None, Field(max_length=512, title='Title')] = ''
    client_id: Annotated[UUID | None, Field(title='Client Id')] = None


class CostAmount(RootModel[str]):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    root: Annotated[
        str, Field(pattern='^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$', title='Cost Amount')
    ]


class DaySlotPayload(BaseModel):
    """
    One day's ordered node ids for the assemble_initial_draft route.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    day_index: Annotated[int, Field(title='Day Index')]
    node_ids_in_order: Annotated[list[UUID], Field(title='Node Ids In Order')]


class DossierDetail(BaseModel):
    """
    Full Dossier typed-core read-through shape.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[UUID, Field(title='Id')]
    contact_preference: ContactChannel
    children_ages: Annotated[list[int], Field(title='Children Ages')]
    travel_party_notes: Annotated[str, Field(title='Travel Party Notes')]
    estimated_net_worth_usd: Annotated[
        int | None, Field(title='Estimated Net Worth Usd')
    ]
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    updated_at: Annotated[AwareDatetime, Field(title='Updated At')]


class SourceKind(StrEnum):
    advisor = 'advisor'
    agent_inferred = 'agent_inferred'


class DossierFactKind(StrEnum):
    """
    Mirrors public.dossier_fact_kind from migration 0011.
    """

    passion = 'passion'
    motivation = 'motivation'
    travel_history = 'travel_history'
    trigger = 'trigger'
    constraint = 'constraint'
    deal_breaker = 'deal_breaker'
    dream_signal = 'dream_signal'
    party = 'party'
    preference = 'preference'
    other = 'other'


class Text(RootModel[str]):
    root: Annotated[str, Field(max_length=4000, min_length=1, title='Text')]


class DossierFactUpdate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: DossierFactKind | None = None
    text: Annotated[Text | None, Field(title='Text')] = None


class ChildrenAge(RootModel[int]):
    root: Annotated[int, Field(ge=0, le=25)]


class EstimatedNetWorthUsd(RootModel[int]):
    root: Annotated[int, Field(ge=0, title='Estimated Net Worth Usd')]


class DossierTyped(BaseModel):
    """
    Typed core of the Dossier — stable structured signals.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    contact_preference: ContactChannel
    children_ages: Annotated[
        list[ChildrenAge] | None, Field(max_length=12, title='Children Ages')
    ] = None
    travel_party_notes: Annotated[
        str | None, Field(max_length=2000, title='Travel Party Notes')
    ] = ''
    estimated_net_worth_usd: Annotated[
        EstimatedNetWorthUsd | None, Field(title='Estimated Net Worth Usd')
    ] = None


class EdgeType(StrEnum):
    """
    Mirrors the public.edge_type Postgres enum.
    """

    follows = 'follows'
    alternative_to = 'alternative_to'
    connected_by = 'connected_by'
    requires = 'requires'
    grouped_with = 'grouped_with'


class EditorialLink(BaseModel):
    """
    A curated external link — article, guide, trip report.
    """

    url: Annotated[str, Field(title='Url')]
    title: Annotated[str | None, Field(title='Title')] = None


class FactSourceKind(StrEnum):
    """
    Mirrors public.fact_source_kind from migration 0011.
    """

    advisor = 'advisor'
    agent_inferred = 'agent_inferred'
    traveler_told = 'traveler_told'
    scraper = 'scraper'


class FindingSeverity(StrEnum):
    """
    Mirrors the public.finding_severity Postgres enum (0017).

    Ordered ``info`` < ``suggest`` < ``warn`` < ``block``. ``block`` is a
    physical impossibility — Fill must not propose candidates that don't
    resolve it.
    """

    info = 'info'
    suggest = 'suggest'
    warn = 'warn'
    block = 'block'


class Status(StrEnum):
    scheduled = 'scheduled'
    boarding = 'boarding'
    in_air = 'in_air'
    landed = 'landed'
    delayed = 'delayed'
    cancelled = 'cancelled'


class FlightStatus(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    flight_code: Annotated[str, Field(title='Flight Code')]
    flight_date: Annotated[date_aliased, Field(title='Flight Date')]
    status: Annotated[Status, Field(title='Status')]
    scheduled_departure: Annotated[AwareDatetime, Field(title='Scheduled Departure')]
    scheduled_arrival: Annotated[AwareDatetime, Field(title='Scheduled Arrival')]
    actual_departure: Annotated[
        AwareDatetime | None, Field(title='Actual Departure')
    ] = None
    actual_arrival: Annotated[AwareDatetime | None, Field(title='Actual Arrival')] = (
        None
    )
    gate: Annotated[str | None, Field(title='Gate')] = None
    terminal: Annotated[str | None, Field(title='Terminal')] = None
    delay_minutes: Annotated[int | None, Field(title='Delay Minutes')] = 0
    aircraft: Annotated[str | None, Field(title='Aircraft')] = None


class GapModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    start: Annotated[AwareDatetime, Field(title='Start')]
    end: Annotated[AwareDatetime, Field(title='End')]


class GeoPoint(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    lat: Annotated[float, Field(title='Lat')]
    lng: Annotated[float, Field(title='Lng')]


class GeoPointResponse(BaseModel):
    lat: Annotated[float, Field(title='Lat')]
    lng: Annotated[float, Field(title='Lng')]


class HealthResponse(BaseModel):
    status: Annotated[str, Field(title='Status')]


class Status1(StrEnum):
    active = 'active'
    consumed = 'consumed'
    cancelled = 'cancelled'
    superseded = 'superseded'


class InviteEvent(BaseModel):
    """
    A single invite send — one row in the invite history for a client.

    The raw ``code`` is deliberately omitted. Codes are bearer credentials;
    the advisor UI needs timestamps + lifecycle state to render the history,
    not the codes themselves.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    consumed_at: Annotated[AwareDatetime | None, Field(title='Consumed At')]
    cancelled_at: Annotated[AwareDatetime | None, Field(title='Cancelled At')]
    superseded_at: Annotated[AwareDatetime | None, Field(title='Superseded At')]
    status: Annotated[Status1, Field(title='Status')]


class ItineraryStatus(StrEnum):
    """
    Mirrors the public.itinerary_status Postgres enum (0006).
    """

    draft = 'draft'
    approved = 'approved'


class JapanInstantiateRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    client_id: Annotated[UUID, Field(title='Client Id')]
    trip_start_at: Annotated[
        AwareDatetime | None,
        Field(
            description='Trip start anchor. Defaults to 30 days from now at midnight UTC.',
            title='Trip Start At',
        ),
    ] = None
    title: Annotated[str | None, Field(title='Title')] = None


class JapanInstantiateResponse(BaseModel):
    itinerary_id: Annotated[UUID, Field(title='Itinerary Id')]
    template_slug: Annotated[str, Field(title='Template Slug')]
    template_version: Annotated[int, Field(title='Template Version')]
    trip_start_at: Annotated[AwareDatetime, Field(title='Trip Start At')]
    node_count: Annotated[int, Field(title='Node Count')]
    edge_count: Annotated[int, Field(title='Edge Count')]


class Location(BaseModel):
    """
    Geographic anchor for an inventory item.
    """

    lat: Annotated[float | None, Field(title='Lat')] = None
    lng: Annotated[float | None, Field(title='Lng')] = None
    label: Annotated[str | None, Field(title='Label')] = None


class LoginRequest(BaseModel):
    """
    Payload for ``POST /auth/login``.
    """

    email: Annotated[EmailStr, Field(title='Email')]


class MyClientResponse(BaseModel):
    """
    Response for ``GET /me/client`` — the client_id the caller belongs to.
    """

    client_id: Annotated[UUID, Field(title='Client Id')]


class MyItinerarySummary(BaseModel):
    """
    Row shape for ``GET /me/itineraries``.
    """

    id: Annotated[UUID, Field(title='Id')]
    title: Annotated[str, Field(title='Title')]
    status: ItineraryStatus
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    updated_at: Annotated[AwareDatetime, Field(title='Updated At')]
    approved_at: Annotated[AwareDatetime | None, Field(title='Approved At')]


class MyOnboardingSessionResponse(BaseModel):
    """
    Summary of the calling client's most-recent ACTIVE agent session.

    ``session_id`` (and the dependent fields ``turn_count``,
    ``last_turn_at``, ``seeded_opener``) describe the current ongoing
    session — i.e. ``ended_at IS NULL``. ``has_prior_session`` is true
    iff the client has any session row at all, ended or not. Basecamp
    uses ``has_prior_session`` (rather than ``turn_count > 0``) to gate
    the first-prompt opener UI so a user who clicks Skip / Close is not
    re-shown the opener on the next page load.

    All session-scoped fields are null when no active session exists.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    session_id: Annotated[UUID | None, Field(title='Session Id')]
    turn_count: Annotated[int, Field(title='Turn Count')]
    last_turn_at: Annotated[AwareDatetime | None, Field(title='Last Turn At')]
    seeded_opener: Annotated[str | None, Field(title='Seeded Opener')]
    has_prior_session: Annotated[bool, Field(title='Has Prior Session')]


class NodeStatus(StrEnum):
    """
    Mirrors the public.node_status Postgres enum.
    """

    idea = 'idea'
    proposed = 'proposed'
    approved = 'approved'
    booked = 'booked'
    confirmed = 'confirmed'
    discarded = 'discarded'


class NodeType(StrEnum):
    """
    Mirrors the public.node_type Postgres enum.

    0002_itinerary_graph.sql introduced the original 8 values; 0014 added
    the per-mode transit kinds (subway/train/drive/walk/boat) and `waiting`
    so each card kind carries its own signature detail per the cards style
    guide. `transit` and `destination` remain valid for legacy rows but
    Phase 2+ writes prefer the granular kinds.
    """

    destination = 'destination'
    flight = 'flight'
    hotel = 'hotel'
    experience = 'experience'
    meal = 'meal'
    transit = 'transit'
    free_time = 'free_time'
    note = 'note'
    subway = 'subway'
    train = 'train'
    drive = 'drive'
    walk = 'walk'
    boat = 'boat'
    waiting = 'waiting'


class OnboardingOpenerResponse(BaseModel):
    """
    One randomly-chosen opening question for a brand-new client.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[UUID, Field(title='Id')]
    prompt: Annotated[str, Field(title='Prompt')]


class SeededOpener(RootModel[str]):
    root: Annotated[str, Field(max_length=500, title='Seeded Opener')]


class SourceKind1(StrEnum):
    advisor = 'advisor'
    scraper = 'scraper'


class OsintFactKind(StrEnum):
    """
    Mirrors public.osint_fact_kind from migration 0011.
    """

    linkedin = 'linkedin'
    facebook = 'facebook'
    instagram = 'instagram'
    press = 'press'
    company = 'company'
    public_record = 'public_record'
    other = 'other'


class OsintFactUpdate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: OsintFactKind | None = None
    text: Annotated[Text | None, Field(title='Text')] = None


class PlacePhoto(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    photo_reference: Annotated[str, Field(title='Photo Reference')]
    width: Annotated[int, Field(title='Width')]
    height: Annotated[int, Field(title='Height')]


class PlaceSummary(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    place_id: Annotated[str, Field(title='Place Id')]
    name: Annotated[str, Field(title='Name')]
    location: GeoPoint
    types: Annotated[list[str], Field(title='Types')]
    rating: Annotated[float | None, Field(title='Rating')] = None


class Price(BaseModel):
    """
    Price range — providers often return a min/max per-person figure.
    """

    amount_min: Annotated[float | None, Field(title='Amount Min')] = None
    amount_max: Annotated[float | None, Field(title='Amount Max')] = None
    currency: Annotated[str | None, Field(title='Currency')] = None


class SourceKind2(StrEnum):
    advisor = 'advisor'
    traveler_told = 'traveler_told'


class ProfileFactKind(StrEnum):
    """
    Mirrors public.profile_fact_kind from migration 0011.
    """

    passion = 'passion'
    motivation = 'motivation'
    travel_history = 'travel_history'
    trigger = 'trigger'
    constraint = 'constraint'
    deal_breaker = 'deal_breaker'
    dream_signal = 'dream_signal'
    preference = 'preference'
    aspiration = 'aspiration'
    other = 'other'


class ProfileFactUpdate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: ProfileFactKind | None = None
    text: Annotated[Text | None, Field(title='Text')] = None


class Range(BaseModel):
    """
    Inclusive numeric range used for duration_days, difficulty, etc.
    """

    min: Annotated[float | None, Field(title='Min')] = None
    max: Annotated[float | None, Field(title='Max')] = None


class RedactRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    reason: Annotated[str, Field(max_length=1000, min_length=1, title='Reason')]


class RedeemInviteRequest(BaseModel):
    """
    Payload for ``POST /auth/redeem-invite``.

    Both fields are required; whitespace is trimmed at the service layer.
    """

    code: Annotated[str, Field(max_length=128, min_length=1, title='Code')]
    email: Annotated[EmailStr, Field(title='Email')]


class RadiusM(RootModel[int]):
    root: Annotated[int, Field(ge=1, le=50000, title='Radius M')]


class SearchRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    query: Annotated[str, Field(title='Query')]
    near: GeoPoint | None = None
    radius_m: Annotated[RadiusM | None, Field(title='Radius M')] = None


class SearchResponse(BaseModel):
    results: Annotated[list[PlaceSummary], Field(title='Results')]


class SessionAudience(StrEnum):
    """
    Mirrors the public.session_audience enum from 0018.

    Splits the client-facing conversation from a private advisor workspace:
    ``traveler`` is the shared thread (the traveler + any advisor who joins);
    ``advisor`` is the advisor<->AI session the traveler never sees.
    """

    traveler = 'traveler'
    advisor = 'advisor'


class StartAnalysisRequest(BaseModel):
    depth: AnalysisDepth | None = 'standard'
    scope: Annotated[dict[str, Any] | None, Field(title='Scope')] = None
    force_rerun: Annotated[bool | None, Field(title='Force Rerun')] = False


class TransitItem(BaseModel):
    source: Annotated[str, Field(title='Source')]
    source_id: Annotated[str, Field(title='Source Id')]
    title: Annotated[str, Field(title='Title')]
    description: Annotated[str | None, Field(title='Description')] = None
    photos: Annotated[list[str] | None, Field(title='Photos')] = []
    location: Location | None = None
    price: Price | None = None
    editorial_links: Annotated[
        list[EditorialLink] | None,
        Field(title='Editorial Links', validate_default=True),
    ] = []
    tags: Annotated[list[str] | None, Field(title='Tags')] = []
    raw: Annotated[dict[str, Any] | None, Field(title='Raw')] = {}
    kind: Annotated[Literal['transit'], Field(title='Kind')] = 'transit'
    mode: Annotated[str | None, Field(title='Mode')] = None


class TurnRequest(BaseModel):
    """
    Body of ``POST /sessions/{session_id}/turn``.

    ``content`` is bounded to 8000 chars to cap payload amplification into
    the Bedrock model context (threat surface). Empty strings are 422.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    content: Annotated[str, Field(max_length=8000, min_length=1, title='Content')]


class TurnRole(StrEnum):
    """
    Mirrors the public.turn_role Postgres enum from 0004_agent_sessions.sql.
    """

    user = 'user'
    assistant = 'assistant'
    system = 'system'
    tool = 'tool'
    error = 'error'


class UpdateNodeRequest(BaseModel):
    """
    Partial update. Any field omitted is left unchanged.

    ``model_config`` uses ``extra="forbid"`` so a misspelled field surfaces
    as 422, not a silent no-op.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: NodeType | None = None
    status: NodeStatus | None = None
    title: Annotated[str | None, Field(title='Title')] = None
    source: Annotated[str | None, Field(title='Source')] = None
    source_id: Annotated[str | None, Field(title='Source Id')] = None
    metadata: Annotated[dict[str, Any] | None, Field(title='Metadata')] = None
    cost_amount: Annotated[float | CostAmount | None, Field(title='Cost Amount')] = None
    cost_currency: Annotated[str | None, Field(title='Cost Currency')] = None
    cost_kind: CostKind | None = None


class ValidationError(BaseModel):
    loc: Annotated[list[str | int], Field(title='Location')]
    msg: Annotated[str, Field(title='Message')]
    type: Annotated[str, Field(title='Error Type')]


class WeatherForecast(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    lat: Annotated[float, Field(title='Lat')]
    lng: Annotated[float, Field(title='Lng')]
    date: Annotated[date_aliased, Field(title='Date')]
    condition: Annotated[str, Field(title='Condition')]
    emoji: Annotated[str, Field(title='Emoji')]
    temp_c_high: Annotated[float, Field(title='Temp C High')]
    temp_c_low: Annotated[float, Field(title='Temp C Low')]
    precipitation_chance: Annotated[float, Field(title='Precipitation Chance')]
    summary: Annotated[str, Field(title='Summary')]


class AdvisorItinerarySummary(BaseModel):
    """
    Row shape for the advisor roster of itineraries.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[UUID, Field(title='Id')]
    title: Annotated[str, Field(title='Title')]
    status: ItineraryStatus
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    updated_at: Annotated[AwareDatetime, Field(title='Updated At')]
    approved_at: Annotated[AwareDatetime | None, Field(title='Approved At')]
    last_activity_at: Annotated[AwareDatetime, Field(title='Last Activity At')]
    client: AdvisorItineraryClient
    needs_attention: Annotated[Literal[False], Field(title='Needs Attention')] = False


class AgentRecordDossierInferenceRequest(BaseModel):
    """
    Body for ``POST /agent/dossier/facts`` (agent-only).

    The endpoint always stamps ``source_kind=agent_inferred``.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    kind: DossierFactKind
    text: Annotated[str, Field(max_length=4000, min_length=1, title='Text')]
    source_turn_id: Annotated[UUID | None, Field(title='Source Turn Id')] = None


class AgentRecordProfileFactRequest(BaseModel):
    """
    Body for ``POST /agent/profile/facts`` (agent-only).

    The endpoint always stamps ``source_kind=traveler_told`` regardless of
    what the agent might supply — so the field is not part of the request
    shape. ``source_turn_id`` is optional context the agent can attach so
    the command center can link the fact back to the originating turn.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    kind: ProfileFactKind
    text: Annotated[str, Field(max_length=4000, min_length=1, title='Text')]
    source_turn_id: Annotated[UUID | None, Field(title='Source Turn Id')] = None


class AgentTurnSummary(BaseModel):
    """
    Row shape for ``GET /sessions/{session_id}/turns``.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[UUID, Field(title='Id')]
    turn_index: Annotated[int, Field(title='Turn Index')]
    role: TurnRole
    content: Annotated[str, Field(title='Content')]
    model: Annotated[str | None, Field(title='Model')]
    latency_ms: Annotated[int | None, Field(title='Latency Ms')]
    first_token_ms: Annotated[int | None, Field(title='First Token Ms')]
    retried: Annotated[int, Field(title='Retried')]
    error_reason: Annotated[str | None, Field(title='Error Reason')]
    created_at: Annotated[AwareDatetime, Field(title='Created At')]


class AnalysisCreatedResponse(BaseModel):
    analysis_id: Annotated[UUID, Field(title='Analysis Id')]
    status: AnalysisStatus
    cache_hit: Annotated[bool | None, Field(title='Cache Hit')] = False
    in_flight: Annotated[bool | None, Field(title='In Flight')] = False


class AssembleDraftRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    day_plan: Annotated[list[DaySlotPayload] | None, Field(title='Day Plan')] = None


class ClientContactCreate(BaseModel):
    """
    POST body for creating a contact row.

    Used both as a top-level create payload and as an embedded element of
    :class:`app.schemas.clients.ClientCreatePayload` when seeding contacts
    atomically at client-creation time.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    kind: ContactKind
    value: Annotated[str, Field(max_length=256, min_length=1, title='Value')]
    label: Annotated[str | None, Field(max_length=64, title='Label')] = ''


class ClientContactDetail(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[UUID, Field(title='Id')]
    kind: ContactKind
    value: Annotated[str, Field(title='Value')]
    label: Annotated[str, Field(title='Label')]
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    updated_at: Annotated[AwareDatetime, Field(title='Updated At')]


class ClientContactUpdate(BaseModel):
    """
    PATCH body — every field is optional; omitted fields stay unchanged.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    kind: ContactKind | None = None
    value: Annotated[Value | None, Field(title='Value')] = None
    label: Annotated[Label | None, Field(title='Label')] = None


class CreateEdgeRequest(BaseModel):
    from_node_id: Annotated[UUID, Field(title='From Node Id')]
    to_node_id: Annotated[UUID, Field(title='To Node Id')]
    type: EdgeType
    metadata: Annotated[dict[str, Any] | None, Field(title='Metadata')] = None


class CreateNodeFromInventoryRequest(BaseModel):
    """
    Create a graph node from a live inventory item by (source, source_id).

    The server fetches the current item through the provider registry and
    derives the typed card metadata (e.g. a Duffel flight → FlightCardAttrs),
    so callers never hand-shape card attrs. For flights this re-fetch is a
    natural offer refresh (D024). ``status`` defaults to ``proposed`` — the
    item is a candidate on the board, not a stray idea.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    source: Annotated[str, Field(title='Source')]
    source_id: Annotated[str, Field(title='Source Id')]
    status: NodeStatus | None = 'proposed'
    parent_subgraph_id: Annotated[UUID | None, Field(title='Parent Subgraph Id')] = None


class CreateNodeRequest(BaseModel):
    type: NodeType
    status: NodeStatus | None = 'idea'
    title: Annotated[str | None, Field(title='Title')] = ''
    parent_subgraph_id: Annotated[UUID | None, Field(title='Parent Subgraph Id')] = None
    source: Annotated[str | None, Field(title='Source')] = None
    source_id: Annotated[str | None, Field(title='Source Id')] = None
    metadata: Annotated[dict[str, Any] | None, Field(title='Metadata')] = None
    cost_amount: Annotated[float | CostAmount | None, Field(title='Cost Amount')] = None
    cost_currency: Annotated[str | None, Field(title='Cost Currency')] = None
    cost_kind: CostKind | None = None


class DestinationItem(BaseModel):
    source: Annotated[str, Field(title='Source')]
    source_id: Annotated[str, Field(title='Source Id')]
    title: Annotated[str, Field(title='Title')]
    description: Annotated[str | None, Field(title='Description')] = None
    photos: Annotated[list[str] | None, Field(title='Photos')] = []
    location: Location | None = None
    price: Price | None = None
    editorial_links: Annotated[
        list[EditorialLink] | None,
        Field(title='Editorial Links', validate_default=True),
    ] = []
    tags: Annotated[list[str] | None, Field(title='Tags')] = []
    raw: Annotated[dict[str, Any] | None, Field(title='Raw')] = {}
    kind: Annotated[Literal['destination'], Field(title='Kind')] = 'destination'


class DossierFactCreate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: DossierFactKind
    text: Annotated[str, Field(max_length=4000, min_length=1, title='Text')]
    source_kind: Annotated[SourceKind | None, Field(title='Source Kind')] = 'advisor'
    source_ref: Annotated[dict[str, Any] | None, Field(title='Source Ref')] = None
    observed_at: Annotated[AwareDatetime | None, Field(title='Observed At')] = None


class DossierFactDetail(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[UUID, Field(title='Id')]
    kind: DossierFactKind
    text: Annotated[str, Field(title='Text')]
    source_kind: FactSourceKind
    source_ref: Annotated[dict[str, Any], Field(title='Source Ref')]
    observed_at: Annotated[AwareDatetime, Field(title='Observed At')]
    recorded_by: Annotated[UUID, Field(title='Recorded By')]
    redacted_at: Annotated[AwareDatetime | None, Field(title='Redacted At')]
    redacted_by: Annotated[UUID | None, Field(title='Redacted By')]
    redacted_reason: Annotated[str | None, Field(title='Redacted Reason')]
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    updated_at: Annotated[AwareDatetime, Field(title='Updated At')]


class DossierPayload(BaseModel):
    """
    Wrapper kept for backward-compat parity with the prior payload shape.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    typed: DossierTyped


class EdgeResponse(BaseModel):
    id: Annotated[UUID, Field(title='Id')]
    itinerary_id: Annotated[UUID, Field(title='Itinerary Id')]
    from_node_id: Annotated[UUID, Field(title='From Node Id')]
    to_node_id: Annotated[UUID, Field(title='To Node Id')]
    type: EdgeType
    metadata: Annotated[dict[str, Any], Field(title='Metadata')]


class ExperienceItem(BaseModel):
    source: Annotated[str, Field(title='Source')]
    source_id: Annotated[str, Field(title='Source Id')]
    title: Annotated[str, Field(title='Title')]
    description: Annotated[str | None, Field(title='Description')] = None
    photos: Annotated[list[str] | None, Field(title='Photos')] = []
    location: Location | None = None
    price: Price | None = None
    editorial_links: Annotated[
        list[EditorialLink] | None,
        Field(title='Editorial Links', validate_default=True),
    ] = []
    tags: Annotated[list[str] | None, Field(title='Tags')] = []
    raw: Annotated[dict[str, Any] | None, Field(title='Raw')] = {}
    kind: Annotated[Literal['experience'], Field(title='Kind')] = 'experience'
    duration_days: Range | None = None
    difficulty: Range | None = None


class FillProposalResponse(BaseModel):
    inventory_source: Annotated[str, Field(title='Inventory Source')]
    inventory_id: Annotated[str, Field(title='Inventory Id')]
    title: Annotated[str, Field(title='Title')]
    type: NodeType
    starts_at: Annotated[AwareDatetime, Field(title='Starts At')]
    ends_at: Annotated[AwareDatetime, Field(title='Ends At')]
    location: GeoPointResponse | None
    score: Annotated[float, Field(title='Score')]
    fits_in_gap: Annotated[bool, Field(title='Fits In Gap')]
    feasibility_unknown: Annotated[bool, Field(title='Feasibility Unknown')]
    drive_time_in_min: Annotated[int | None, Field(title='Drive Time In Min')]
    drive_time_out_min: Annotated[int | None, Field(title='Drive Time Out Min')]
    party_ok: Annotated[bool, Field(title='Party Ok')]
    constraint_warnings: Annotated[list[str], Field(title='Constraint Warnings')]
    rationale: Annotated[str, Field(title='Rationale')]


class FillRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    gap: GapModel
    party_id: Annotated[UUID | None, Field(title='Party Id')] = None
    analysis_id: Annotated[UUID | None, Field(title='Analysis Id')] = None
    desired_kinds: Annotated[list[NodeType] | None, Field(title='Desired Kinds')] = None
    min_score: Annotated[float | None, Field(ge=0.0, le=1.0, title='Min Score')] = 0.5
    max_proposals: Annotated[int | None, Field(ge=1, le=50, title='Max Proposals')] = 8


class FillResponse(BaseModel):
    proposals: Annotated[list[FillProposalResponse], Field(title='Proposals')]
    analysis_id: Annotated[UUID | None, Field(title='Analysis Id')]
    analysis_age_seconds: Annotated[int | None, Field(title='Analysis Age Seconds')]


class FindingResponse(BaseModel):
    id: Annotated[UUID, Field(title='Id')]
    node_id: Annotated[UUID | None, Field(title='Node Id')]
    severity: FindingSeverity
    category: Annotated[str, Field(title='Category')]
    message: Annotated[str, Field(title='Message')]
    evidence: Annotated[dict[str, Any], Field(title='Evidence')]
    suggested_fix: Annotated[dict[str, Any] | None, Field(title='Suggested Fix')]


class FlightItem(BaseModel):
    source: Annotated[str, Field(title='Source')]
    source_id: Annotated[str, Field(title='Source Id')]
    title: Annotated[str, Field(title='Title')]
    description: Annotated[str | None, Field(title='Description')] = None
    photos: Annotated[list[str] | None, Field(title='Photos')] = []
    location: Location | None = None
    price: Price | None = None
    editorial_links: Annotated[
        list[EditorialLink] | None,
        Field(title='Editorial Links', validate_default=True),
    ] = []
    tags: Annotated[list[str] | None, Field(title='Tags')] = []
    raw: Annotated[dict[str, Any] | None, Field(title='Raw')] = {}
    kind: Annotated[Literal['flight'], Field(title='Kind')] = 'flight'


class HTTPValidationError(BaseModel):
    detail: Annotated[list[ValidationError] | None, Field(title='Detail')] = None


class HotelItem(BaseModel):
    source: Annotated[str, Field(title='Source')]
    source_id: Annotated[str, Field(title='Source Id')]
    title: Annotated[str, Field(title='Title')]
    description: Annotated[str | None, Field(title='Description')] = None
    photos: Annotated[list[str] | None, Field(title='Photos')] = []
    location: Location | None = None
    price: Price | None = None
    editorial_links: Annotated[
        list[EditorialLink] | None,
        Field(title='Editorial Links', validate_default=True),
    ] = []
    tags: Annotated[list[str] | None, Field(title='Tags')] = []
    raw: Annotated[dict[str, Any] | None, Field(title='Raw')] = {}
    kind: Annotated[Literal['hotel'], Field(title='Kind')] = 'hotel'
    stars: Annotated[int | None, Field(title='Stars')] = None


class ItineraryResponse(BaseModel):
    id: Annotated[UUID, Field(title='Id')]
    title: Annotated[str, Field(title='Title')]
    client_id: Annotated[UUID | None, Field(title='Client Id')]
    created_by: Annotated[UUID | None, Field(title='Created By')]
    status: ItineraryStatus | None = 'draft'
    approved_by: Annotated[UUID | None, Field(title='Approved By')] = None
    approved_at: Annotated[AwareDatetime | None, Field(title='Approved At')] = None


class MealItem(BaseModel):
    source: Annotated[str, Field(title='Source')]
    source_id: Annotated[str, Field(title='Source Id')]
    title: Annotated[str, Field(title='Title')]
    description: Annotated[str | None, Field(title='Description')] = None
    photos: Annotated[list[str] | None, Field(title='Photos')] = []
    location: Location | None = None
    price: Price | None = None
    editorial_links: Annotated[
        list[EditorialLink] | None,
        Field(title='Editorial Links', validate_default=True),
    ] = []
    tags: Annotated[list[str] | None, Field(title='Tags')] = []
    raw: Annotated[dict[str, Any] | None, Field(title='Raw')] = {}
    kind: Annotated[Literal['meal'], Field(title='Kind')] = 'meal'


class MyItinerariesResponse(BaseModel):
    """
    Envelope for ``GET /me/itineraries``.
    """

    itineraries: Annotated[list[MyItinerarySummary], Field(title='Itineraries')]


class NodeResponse(BaseModel):
    id: Annotated[UUID, Field(title='Id')]
    itinerary_id: Annotated[UUID, Field(title='Itinerary Id')]
    parent_subgraph_id: Annotated[UUID | None, Field(title='Parent Subgraph Id')]
    type: NodeType
    status: NodeStatus
    title: Annotated[str, Field(title='Title')]
    source: Annotated[str | None, Field(title='Source')]
    source_id: Annotated[str | None, Field(title='Source Id')]
    metadata: Annotated[dict[str, Any], Field(title='Metadata')]
    cost_amount: Annotated[CostAmount | None, Field(title='Cost Amount')] = None
    cost_currency: Annotated[str | None, Field(title='Cost Currency')] = None
    cost_kind: CostKind | None = None
    starts_at: Annotated[str | None, Field(title='Starts At')] = None
    duration_minutes: Annotated[int | None, Field(title='Duration Minutes')] = None
    depth: Annotated[int | None, Field(title='Depth')] = None


class NoteItem(BaseModel):
    source: Annotated[str, Field(title='Source')]
    source_id: Annotated[str, Field(title='Source Id')]
    title: Annotated[str, Field(title='Title')]
    description: Annotated[str | None, Field(title='Description')] = None
    photos: Annotated[list[str] | None, Field(title='Photos')] = []
    location: Location | None = None
    price: Price | None = None
    editorial_links: Annotated[
        list[EditorialLink] | None,
        Field(title='Editorial Links', validate_default=True),
    ] = []
    tags: Annotated[list[str] | None, Field(title='Tags')] = []
    raw: Annotated[dict[str, Any] | None, Field(title='Raw')] = {}
    kind: Annotated[Literal['note'], Field(title='Kind')] = 'note'


class OpenSessionRequest(BaseModel):
    """
    Payload for ``POST /sessions``.

    ``itinerary_id`` is optional: pin the session to a specific draft for
    planning mode, or omit for a general session (onboarding / Q&A). A
    session pinned to an approved itinerary serves as a trip-scoped Q&A.

    ``seeded_opener`` is the verbatim opening line the basecamp UI picked
    from the onboarding-opener bank for a brand-new client. It is recorded
    on the session row and replayed on the runtime as a mode-rubric
    directive ("your first message MUST be exactly …") so the agent's
    streamed first turn matches the prompt the user already saw on the
    page. Ignored / persisted-but-no-op for non-onboarding sessions.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    client_id: Annotated[UUID, Field(title='Client Id')]
    itinerary_id: Annotated[UUID | None, Field(title='Itinerary Id')] = None
    seeded_opener: Annotated[SeededOpener | None, Field(title='Seeded Opener')] = None
    audience: SessionAudience | None = 'traveler'


class OpenSessionResponse(BaseModel):
    """
    Response for ``POST /sessions`` — returned on both create and reuse.

    ``itinerary_id`` reflects the session's current pin. ``None`` means the
    session is unpinned — the browser's mood-board aside can either stay
    empty (onboarding / Q&A) or hydrate after the first ``card_proposed``
    frame auto-creates one. ``seeded_opener`` round-trips so the caller
    can verify the persisted value matches what they sent (for reused
    sessions, this may be a value chosen on a prior request).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    session_id: Annotated[UUID, Field(title='Session Id')]
    agentcore_session_id: Annotated[str, Field(title='Agentcore Session Id')]
    itinerary_id: Annotated[UUID | None, Field(title='Itinerary Id')]
    seeded_opener: Annotated[str | None, Field(title='Seeded Opener')] = None
    audience: SessionAudience | None = 'traveler'


class OsintFactCreate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: OsintFactKind
    text: Annotated[str, Field(max_length=4000, min_length=1, title='Text')]
    source_kind: Annotated[SourceKind1 | None, Field(title='Source Kind')] = 'advisor'
    source_ref: Annotated[dict[str, Any] | None, Field(title='Source Ref')] = None
    observed_at: Annotated[AwareDatetime | None, Field(title='Observed At')] = None


class OsintFactDetail(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[UUID, Field(title='Id')]
    kind: OsintFactKind
    text: Annotated[str, Field(title='Text')]
    source_kind: FactSourceKind
    source_ref: Annotated[dict[str, Any], Field(title='Source Ref')]
    observed_at: Annotated[AwareDatetime, Field(title='Observed At')]
    recorded_by: Annotated[UUID, Field(title='Recorded By')]
    redacted_at: Annotated[AwareDatetime | None, Field(title='Redacted At')]
    redacted_by: Annotated[UUID | None, Field(title='Redacted By')]
    redacted_reason: Annotated[str | None, Field(title='Redacted Reason')]
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    updated_at: Annotated[AwareDatetime, Field(title='Updated At')]


class PlaceDetail(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    place_id: Annotated[str, Field(title='Place Id')]
    name: Annotated[str, Field(title='Name')]
    location: GeoPoint
    formatted_address: Annotated[str, Field(title='Formatted Address')]
    types: Annotated[list[str], Field(title='Types')]
    rating: Annotated[float | None, Field(title='Rating')] = None
    user_ratings_total: Annotated[int | None, Field(title='User Ratings Total')] = None
    opening_hours: Annotated[list[str] | None, Field(title='Opening Hours')] = None
    photos: Annotated[list[PlacePhoto] | None, Field(title='Photos')] = None
    website: Annotated[str | None, Field(title='Website')] = None
    phone: Annotated[str | None, Field(title='Phone')] = None


class ProfileFactCreate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: ProfileFactKind
    text: Annotated[str, Field(max_length=4000, min_length=1, title='Text')]
    source_kind: Annotated[SourceKind2 | None, Field(title='Source Kind')] = 'advisor'
    source_ref: Annotated[dict[str, Any] | None, Field(title='Source Ref')] = None
    observed_at: Annotated[AwareDatetime | None, Field(title='Observed At')] = None


class ProfileFactDetail(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[UUID, Field(title='Id')]
    kind: ProfileFactKind
    text: Annotated[str, Field(title='Text')]
    source_kind: FactSourceKind
    source_ref: Annotated[dict[str, Any], Field(title='Source Ref')]
    observed_at: Annotated[AwareDatetime, Field(title='Observed At')]
    recorded_by: Annotated[UUID, Field(title='Recorded By')]
    redacted_at: Annotated[AwareDatetime | None, Field(title='Redacted At')]
    redacted_by: Annotated[UUID | None, Field(title='Redacted By')]
    redacted_reason: Annotated[str | None, Field(title='Redacted Reason')]
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    updated_at: Annotated[AwareDatetime, Field(title='Updated At')]


class ReleaseLockResponse(BaseModel):
    itinerary: ItineraryResponse
    replayed_count: Annotated[int, Field(title='Replayed Count')]


class SearchInventoryResponse(BaseModel):
    items: Annotated[
        list[
            Annotated[
                ExperienceItem
                | DestinationItem
                | HotelItem
                | FlightItem
                | MealItem
                | TransitItem
                | NoteItem,
                Field(discriminator='kind'),
            ]
        ],
        Field(title='Items'),
    ]
    count: Annotated[int, Field(title='Count')]


class AdvisorItinerariesResponse(BaseModel):
    """
    Envelope for ``GET /itineraries`` (advisor).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    itineraries: Annotated[list[AdvisorItinerarySummary], Field(title='Itineraries')]


class AgentContext(BaseModel):
    """
    Single-payload response of ``GET /agent/context``.

    Returned only to the agent (authenticated by the per-session agent
    token) — never to the traveler's browser.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    client_id: Annotated[UUID, Field(title='Client Id')]
    client_full_name: Annotated[str, Field(title='Client Full Name')]
    dossier: DossierDetail | None
    dossier_facts: Annotated[list[DossierFactDetail], Field(title='Dossier Facts')]
    profile_facts: Annotated[list[ProfileFactDetail], Field(title='Profile Facts')]
    osint_facts: Annotated[list[OsintFactDetail], Field(title='Osint Facts')]


class AnalysisDetailResponse(BaseModel):
    id: Annotated[UUID, Field(title='Id')]
    itinerary_id: Annotated[UUID, Field(title='Itinerary Id')]
    status: AnalysisStatus
    depth: AnalysisDepth
    summary: Annotated[str | None, Field(title='Summary')]
    error_detail: Annotated[str | None, Field(title='Error Detail')]
    started_at: Annotated[AwareDatetime | None, Field(title='Started At')]
    completed_at: Annotated[AwareDatetime | None, Field(title='Completed At')]
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    scope: Annotated[dict[str, Any], Field(title='Scope')]
    result: Annotated[dict[str, Any] | None, Field(title='Result')]
    external_calls: Annotated[list[Any], Field(title='External Calls')]
    findings: Annotated[list[FindingResponse], Field(title='Findings')]


class ClientCreatePayload(BaseModel):
    """
    Payload for ``POST /clients``: a new client + their Dossier.

    Three optional initial fact seeds (one per tier) are written in the
    same atomic transaction as the client + dossier rows so onboarding
    stays one round-trip even when the advisor records knowledge across
    all three disclosure tiers up front.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    full_name: Annotated[str, Field(max_length=200, min_length=1, title='Full Name')]
    email: Annotated[EmailStr, Field(title='Email')]
    dossier: DossierPayload
    dossier_facts: Annotated[
        list[DossierFactCreate] | None, Field(title='Dossier Facts')
    ] = None
    profile_facts: Annotated[
        list[ProfileFactCreate] | None, Field(title='Profile Facts')
    ] = None
    osint_facts: Annotated[list[OsintFactCreate] | None, Field(title='Osint Facts')] = (
        None
    )
    contacts: Annotated[list[ClientContactCreate] | None, Field(title='Contacts')] = (
        None
    )


class ClientDetail(BaseModel):
    """
    Full client + dossier + per-tier fact lists for ``GET /clients/{id}``.

    ``invite_history`` lists every send for this client, newest first.
    ``invite_status`` is the derived current state and duplicates what
    the top of ``invite_history`` implies — consumers can read either.

    Fact lists default to active rows only (``redacted_at IS NULL``);
    advisors who want to see redacted history can pass
    ``?include_redacted=1`` on the request.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[UUID, Field(title='Id')]
    full_name: Annotated[str, Field(title='Full Name')]
    email: Annotated[EmailStr, Field(title='Email')]
    invite_status: Annotated[InviteStatus, Field(title='Invite Status')]
    invite_history: Annotated[list[InviteEvent], Field(title='Invite History')]
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    updated_at: Annotated[AwareDatetime, Field(title='Updated At')]
    dossier: DossierDetail | None
    dossier_facts: Annotated[
        list[DossierFactDetail] | None, Field(title='Dossier Facts')
    ] = None
    profile_facts: Annotated[
        list[ProfileFactDetail] | None, Field(title='Profile Facts')
    ] = None
    osint_facts: Annotated[list[OsintFactDetail] | None, Field(title='Osint Facts')] = (
        None
    )
    contacts: Annotated[list[ClientContactDetail] | None, Field(title='Contacts')] = (
        None
    )


class GraphResponse(BaseModel):
    itinerary: ItineraryResponse
    nodes: Annotated[list[NodeResponse], Field(title='Nodes')]
    edges: Annotated[list[EdgeResponse], Field(title='Edges')]
